root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "./tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go", "mod", "sum", "html"]
exclude_ext = ["swp", "tmp"]
log = "build-errors.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true
