root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main ./cmd"
bin = "./tmp/main"
full_bin = "dlv exec ./tmp/main --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient --continue --log"
delay = 1000
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go", "mod", "sum", "templ"]
exclude_ext = ["swp", "tmp"]
exclude_regex = ["views/.*\\.go$"]                     # ignore src/views/*.go
log = "build-errors.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true
